export const Orgaos = [
    "ABNC - Academia Brasileira de Neurocirurgia",
    "AGU - Advocacia-Geral da União",
    "ANAC - Agência Nacional de Aviação Civil",
    "CAER - Clube de Aeronáutica",
    "CAU - Conselho de Arquitetura e Urbanismo",
    "CBM - Corpo de Bombeiro Militar",
    "CFA - Conselho Federal Administração",
    "CFB - Conselho Federal de Biblioteconomia",
    "CFBIO - Conselho Federal de Biologia",
    "CFBM - Conselho Federal de Biomedicina",
    "CFC - Conselho Federal de Contabilidade",
    "CFESS - Conselho Federal de Serviço Social",
    "CFF - Conselho Federal de Farmácia",
    "CFFA - Conselho Federal de Fonoaudiologia",
    "CFM - Conselho Federal de Medicina",
    "CFMV - Conselho Federal de Medicina Veterinária",
    "CFN - Conselho Federal de Nutrição",
    "CFO - Conselho Federal de Odontologia",
    "CFP - Conselho Federal de Psicologia",
    "CFQ - Conselho Federal de Química",
    "CFT - Conselho Federal dos Técnicos Industriais",
    "CFTA - Conselho Federal dos Técnicos Agrícolas",
    "CGPI - Coordenação Geral de Privilégios e Imunidades",
    "CGPMAF - Coordenadoria Geral de Polícia Marítima, Aeronáutica e de Fronteiras",
    "CIPC - Centro de Inteligência da Polícia Civil",
    "CNIG - Conselho Nacional de Imigração",
    "CNT - Confederação Nacional do Transporte",
    "CNTV - Confederação Nacional de Vigilantes & Prestadores de Serviços",
    "COFECI - Conselho Federal de Corretores de Imóveis",
    "COFECON - Conselho Federal de Economia",
    "COFEM - Conselho Federal de Museologia",
    "COFEN - Conselho Federal de Enfermagem",
    "COFFITO - Conselho Federal de Fisioterapia e Terapia Ocupacional",
    "COMAER - Comando da Aeronáutica",
    "CONFE - Conselho Federal de Estatística",
    "CONFEA - Conselho Federal de Engenharia e Agronomia",
    "CONFEF - Conselho Federal de Educação Física",
    "CONFERE - Conselho Federal dos Representantes Comerciais",
    "CONRE - Conselho Regional de Estatística",
    "CONRERP - Conselho Federal de Profissionais de Relações Públicas",
    "CORE - Conselho Regional dos Representantes Comerciais",
    "CORECON - Conselho Regional de Economia",
    "COREM - Conselho Regional de Museologia",
    "COREN - Conselho Regional de Enfermagem",
    "CRA - Conselho Regional de Administração",
    "CRAS - Centro de Referência de Assistência Social",
    "CRB - Conselho Regional de Biblioteconomia",
    "CRBIO - Conselho Regional de Biologia",
    "CRBM - Conselho Regional de Biomedicina",
    "CRC - Conselho Regional de Contabilidade",
    "CREA - Conselho Regional de Engenharia e Agronomia",
    "CRECI - Conselho Regional de Corretores de Imóveis",
    "CREF - Conselho Regional de Educação Física",
    "CREFITO - Conselho Regional de Fisioterapia e Terapia Ocupacional",
    "CRESS - Conselho Regional de Serviço Social",
    "CRF - Conselho Regional de Farmácia",
    "CRFA - Conselho Regional de Fonoaudiologia",
    "CRM - Conselho Regional de Medicina",
    "CRMV - Conselho Regional de Medicina Veterinária",
    "CRN - Conselho Regional de Nutrição",
    "CRO - Conselho Regional de Odontologia",
    "CRP - Conselho Regional de Psicologia",
    "CRPRE - Conselho Regional de Profissionais de Relações Públicas",
    "CRQ - Conselho Regional de Química",
    "CRT - Conselho Regional dos Técnicos Industriais",
    "CRTA - Conselho Regional de Técnicos de Administração",
    "CTPS - Carteira de Trabalho e Previdência Social",
    "CV - Cartório Civil",
    "DELEMIG - Delegacia de Polícia de Imigração",
    "DETRAN - Departamento Estadual de Trânsito",
    "DGPC - Diretoria Geral da Polícia Civil",
    "DIC - Diretoria de Identificação Civil",
    "DICC - Diretoria de Identificação Civil e Criminal",
    "DIREX - Diretoria Executiva",
    "DPF - Departamento de Polícia Federal",
    "DPMAF - Divisão de Polícia Marítima, Aérea e de Fronteiras",
    "DPT - Departamento de Polícia Técnica Geral",
    "DPTC - Departamento de Polícia Técnico Científica",
    "DREX - Delegacia Regional Executiva",
    "DRT - Delegacia Regional do Trabalho",
    "EB - Exército Brasileiro",
    "IBGE - Instituto Brasileiro de Geografia e Estatística",
    "INSS - Instituto Nacional do Seguro Social",
    "IOM - Instituto Oscar Freire",
    "ITI - Instituto Nacional de Tecnologia da Informação",
    "JF - Justiça Federal",
    "MAM - Marinha Mercante",
    "MArAer - Ministério da Aeronáutica",
    "MB - Marinha do Brasil",
    "MCTIC - Ministério da Ciência, Tecnologia, Inovações e Comunicações",
    "MEX - Ministério do Exército",
    "MJ - Ministério da Justiça",
    "MMA - Ministério do Meio Ambiente",
    "MMDC - Monumento Mausoléu ao Soldado Constitucionalista",
    "MP - Ministério Público",
    "MPDFT - Ministério Público do Distrito Federal e Territórios",
    "MPE - Ministério Público Estadual",
    "MPF - Ministério Público Federal",
    "MPT - Ministério Público do Trabalho",
    "MPU - Ministério Público da União",
    "MRE - Ministério das Relações Exteriores",
    "MS - Ministério da Saúde",
    "NE - Notório Especialista",
    "OAB - Ordem dos Advogados do Brasil",
    "ONU - Organização das Nações Unidas",
    "PC - Polícia Civil",
    "PCF - Polícia Civil Federal",
    "PCT - Posto de Controle de Trafego",
    "PF - Polícia Federal",
    "PM - Polícia Militar",
    "PMF - Polícia Militar Federal",
    "PMI - Polícia Marítima",
    "PMM - Polícia Militar Marítima",
    "PMMG - Polícia Militar do Estado de Minas Gerais",
    "PMPA - Polícia Militar do Estado do Pará",
    "PMSP - Polícia Militar do Estado de São Paulo",
    "PRF - Polícia Rodoviária Federal",
    "RF - Receita Federal",
    "SIC - Secretaria de Identificação Civil",
    "SIP - Sistema Penitenciário",
    "SPF - Secretaria de Polícia Federal",
    "SRF - Secretaria da Receita Federal",
    "STM - Superior Tribunal Militar",
    "STT - Secretaria dos Transportes",
    "SUS - Sistema Único de Saúde",
    "TC - Tribunal de Contas",
    "TCE - Tribunal de Contas do Estado",
    "TCM - Tribunal de Contas do Município",
    "TCU - Tribunal de Contas da União",
    "TJ - Tribunal de Justiça",
    "TRE - Tribunal Regional Eleitoral",
    "TRF - Tribunal Regional Federal",
    "TRT - Tribunal Regional do Trabalho",
    "TSE - Tribunal Superior Eleitoral",
    "XXX - Orgão Estrangeiro",
    "ZZZ - Outro"
];