export const keyMapping = {
    "ID": "id",
    "Tipo": "tipo",
    "Função": "funcao",
    "Nome": "nome",
    "CPF": "cpf",
    "Identidade": "identidade",
    "Órgão Expedidor": "orgaoExpedidor",
    "Data de Nascimento": "dataNascimento",
    "Profissão": "profissao",
    "Estado Civil": "estadoCivil",
    "Nacionalidade": "nacionalidade",
    "Telefone Fixo": "telefoneFixo",
    "Telefone Celular": "telefoneCelular", 
    "E-mail": "email",
    "mae": "filiacao.mae",
    "pai": "filiacao.pai",
    "rua": "endereco.rua",
    "Numero": "endereco.numero",
    "Complemento": "endereco.complemento",
    "Bairro": "endereco.bairro",
    "Cidade": "endereco.cidade",
    "Estado": "endereco.estado",
    "Endereco": "endereco.endereco",
    "CEP": "endereco.cep",
    "Banco": "dadoBancarios.banco", 
    "Conta": "dadoBancarios.conta", 
    "Agencia": "dadoBancarios.agencia",
    "ChavePix": "dadoBancarios.chavePix"
};