export const keyMapping = {
    "ID": "id",
    "TipoImovel": "tipoImovel",
    "GeneroImovel": "generoImovel",
    "AreaUtil": "caracteristicas.areaUtil",
    "AreaTotal": "caracteristicas.areaTotal",
    "NumerodeBanheiros": "caracteristicas.numeroBanheiros",
    "NumerodeSuites": "caracteristicas.numeroSuites",
    "NumerodeQuartos": "caracteristicas.numeroQuartos",
    "NumerodeVagas": "caracteristicas.numeroVagas",
    "TipodeConstrucao": "caracteristicas.tipoConstrucao",
    "CEP": "localizacao.cep",
    "Andar": "localizacao.andar",
    "Bairro": "localizacao.bairro",
    "Cidade": "localizacao.cidade",
    "Estado": "localizacao.estado",
    "Numero": "localizacao.numero",
    "Endereco": "localizacao.endereco",
    "ValorMensal": "iptu.valorMensal",
    "NumerodeMatriculaIPTU": "iptu.numero_matricula_iptu",
    "Percentual": "percentual",
    "Tipo": "negociacao.Tipo",

    "ValordeVenda": "valores.valorVenda",
    "TaxadeLocacao": "valores.taxaLocacao",
    "ValordeAluguel": "valores.valorAluguel",
    "TaxadeAdministracao": "valores.taxaAdministracao",
    "TaxadeIntermediacao": "valores.taxaIntermediacao",
    "TaxadeAdministracaoVeA": "valores.vendaealuguelTaxa",
    "ValordeVendaVeA": "valores.vendaealuguelVenda",
    "ValordeAluguelVeA": "valores.vendaealuguelAluguel"
}