export const keyMapping = {
    "ID": "id",
    "TipoImovel": "tipoImovel",
    "GeneroImovel": "generoImovel",
    "AreaUtil": "caracteristicas.areaUtil",
    "AreaTotal": "caracteristicas.areaTotal",
    "NumerodeBanheiros": "caracteristicas.numeroBanheiros",
    "NumerodeSuites": "caracteristicas.numeroSuites",
    "NumerodeQuartos": "caracteristicas.numeroQuartos",
    "NumerodeVagas": "caracteristicas.numeroVagas",
    "TipodeConstrucao": "caracteristicas.tipoConstrucao",
    "CEP": "localizacao.cep",
    "Complemento": "localizacao.andar",
    "Bairro": "localizacao.bairro",
    "Cidade": "localizacao.cidade",
    "Estado": "localizacao.estado",
    "Numero": "localizacao.numero",
    "Endereco": "localizacao.endereco",
    "ValorMensal": "iptu.valorMensal",
    "NumerodeMatriculaIPTU": "iptu.numero_matricula_iptu",
    "Percentual": "percentual",
    "Tipo": "negociacao.Tipo",

    "Valor de Venda": "valores.valorVenda",
    "Taxa de Locacao": "valores.taxaLocacao",
    "Valor de Aluguel": "valores.valorAluguel",
    "Taxa de Administração": "valores.taxaAdministracao",
    "Taxa de Intermediacao": "valores.taxaIntermediacao",
    "Taxa de Administracao - Venda e Aluguel": "valores.vendaealuguelTaxa",
    "Valor de VendaVeA": "valores.vendaealuguelVenda",
    "ValordeAluguelVeA": "valores.vendaealuguelAluguel",

    "CNPJ": "condominio.cnpj",
    "Site": "condominio.site",
    "Login": "condominio.login",
    "Senha": "condominio.senha",
    "Razão Social": "condominio.razao_social",

    "Telefone Fixo": "condominio.telefone_fixo",
    "Telefone Celular": "condominio.telefone_celular",
}